# =============================================================================
# Secrets Manager — EKS Kubeconfig
# Stores the EKS kubeconfig so MWAA workers can authenticate to the cluster
# at runtime when using KubernetesPodOperator
# =============================================================================
resource "aws_secretsmanager_secret" "kubeconfig" {
  name        = "${var.project_name}-${var.environment}-eks-kubeconfig"
  description = "EKS kubeconfig for MWAA KubernetesPodOperator — auto-generated by Terraform"

  tags = merge(local.common_tags, {
    Name = "${var.project_name}-${var.environment}-eks-kubeconfig"
  })
}

# =============================================================================
# Kubeconfig Secret Value
# Builds a kubeconfig that uses AWS CLI token auth (exec-based)
# MWAA workers call "aws eks get-token" at runtime to get short-lived credentials
# No static credentials stored — token is fetched fresh per task
# =============================================================================
resource "aws_secretsmanager_secret_version" "kubeconfig" {
  secret_id = aws_secretsmanager_secret.kubeconfig.id

  secret_string = jsonencode({
    apiVersion      = "v1"
    kind            = "Config"
    current-context = var.cluster_name
    preferences     = {}

    clusters = [{
      name = var.cluster_name
      cluster = {
        certificate-authority-data = var.cluster_ca_certificate
        server                     = var.cluster_endpoint
      }
    }]

    contexts = [{
      name = var.cluster_name
      context = {
        cluster = var.cluster_name
        user    = var.cluster_name
      }
    }]

    users = [{
      name = var.cluster_name
      user = {
        exec = {
          apiVersion = "client.authentication.k8s.io/v1beta1"
          command    = "aws"
          args = [
            "eks", "get-token",
            "--cluster-name", var.cluster_name,
            "--region", var.aws_region
          ]
        }
      }
    }]
  })
}
